- name: Check for gp2 volumes less than 1GB
  shell: >
      aws ec2 describe-volumes --filters "Name=volume-type,Values=gp2" "Name=tag:Environment,Values=UAT" --query 'Volumes[?Size < `1001`].[VolumeId]' --region "{{region}}"
  register: ebs_info

- set_fact:
    ebs_info: "{{ebs_info.stdout | from_json}}"

- name: Upgrade to gp3
  shell: >
     aws ec2 modify-volume --volume-type gp3 --volume-id "{{item}}" --region "{{region}}"
  with_items: "{{ebs_info}}"
  register: result
