- name: Describe EBS volumes using ansible module
  ec2_vol_info:
     region: "{{region}}"
     filters:
       encrypted: false
       attachment.status: attached
  register: ebs_info

- ec2_instance_info:
     region: "{{region}}"
     instance_ids: "{{item}}"
  with_items: "{{ebs_info | json_query ('volumes[*].attachment_set[*].instance_id') | unique}}"
  register: faulty_ec2s

- debug:
    msg: "{{region}} {{faulty_ec2s | json_query ('results[*].instances[*].tags.Name') | length }} instances "
- debug:
    msg: "{{faulty_ec2s | json_query ('results[*].instances[*].tags.Name')}}"

