- name: Get the status of the request
  command:
    aws organizations list-create-account-status
  register: this_request

- name: Store the info
  set_fact:
    txt: "{{this_request.stdout |from_json| json_query (' CreateAccountStatuses ')}}"

- set_fact:
    this_acc_id: "{{txt.0.AccountId}}"

- name: Describe this account
  command:
    aws organizations describe-account --account-id "{{this_acc_id}}"
  register: this_acc_desc

- set_fact:
    this_acc_email: "{{this_acc_desc.stdout |from_json| json_query (' Account.Email ')}}" 


- name: Enable GuardDuty membership for this account in  eu-west-2
  shell: >
       aws guardduty list-members --detector-id 44be7a814ddfa51917b91199c079880f --region eu-west-2  | grep -q "{{this_acc_id}}" && echo 'Attached' || aws guardduty create-members --detector-id 44be7a814ddfa51917b91199c079880f --account-details AccountId="{{this_acc_id}}",Email="{{this_acc_email}}" --region eu-west-2 
  register: gdmember_cli
  changed_when: gdmember_cli.stdout != 'Attached'

- debug:
    msg: "{{gdmember_cli.stdout}}"

