- name: Create Default Production Security Group
  ec2_group:
    name: "{{regionname}}-{{customer}}p-MyOrgdefaultsg1"
    description: MyOrg default ports
    vpc_id: "{{ thisvpc.vpc.id }}"
    region: "{{ region }}"
    state: present
    purge_rules: yes
    purge_rules_egress: yes
    purge_tags: yes
    tags:
      Customer: "{{customer}}"
      Createdby: "{{createdby }}" 
      Environment: Production
    rules:
      - proto: tcp
        ports:
        - 443
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: https
      - proto: tcp
        ports:
        - 22
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: ssh
      - proto: tcp
        ports:
        - 9100
        - 9101
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: prometheus scrape
      - proto: icmp
        ports:
        - -1
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: ping
    rules_egress:
      - proto: all
        ports:
        - -1
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all outbound
  register: thissg
  environment: "{{acc_env}}"
  when: peerings.0.p_cidr is defined

- name: Create UAT Default Security Group
  ec2_group:
    name: "{{regionname}}-{{customer}}u-MyOrgdefaultsg1"
    description: MyOrg default ports
    vpc_id: "{{ thisvpc.vpc.id }}"
    region: "{{ region }}"
    state: present
    purge_rules: yes
    purge_rules_egress: yes
    purge_tags: yes
    tags:
      Customer: "{{customer}}"
      Createdby: "{{createdby }}" 
      Environment: UAT
    rules:
      - proto: tcp
        ports:
          - 443
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: https
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: ssh
      - proto: tcp
        ports:
          - 9100
          - 9101
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: prometheus scrape
      - proto: icmp
        ports:
          - -1
        cidr_ip: "{{peerings.0.p_cidr}}"
        rule_desc: ping
    rules_egress:
      - proto: all
        ports:
        - -1
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all outbound
  register: thissg
  environment: "{{acc_env}}"
  when: peerings.0.p_cidr is defined

