### sudo ansible-playbook plays/disable_dd_in_uat.yml --private-key ~/.ssh/ssh-key.pem -i disable_dd_in_uat_aws_ec2.yml

- name: Disable and stop datadog-agent in UAT instances
  hosts: all

  tasks:    
    - name: Datadog is running when result is not Stopped
      shell: >
        systemctl status datadog-agent  | grep -q '(running)'  && sudo systemctl disable datadog-agent || echo 'Stopped'
      register: dd1_cli
      changed_when: dd1_cli.stdout != 'Stopped'
      
    - debug:
        msg: "{{dd1_cli.stdout}}"

    - name: Datadog is running when result is not Stopped
      shell: >
        systemctl status datadog-agent  | grep -q '(running)'  && sudo systemctl stop datadog-agent || echo 'Stopped'
      register: dd2_cli
      changed_when: dd2_cli.stdout != 'Stopped'
      
    - debug:
        msg: "{{dd2_cli.stdout}}"

