### sudo ansible-playbook plays/dd_report_log4j.yml --private-key ~/.ssh/ssh-key.pem -i dd_report_log4j_aws_ec2.yml > file.txt
### more file.txt | grep changed: 
 
- name: List of linux instances with log4j hotpatch installed and enabled  
  hosts: all

  tasks:
    - name: log4j is installed when result equals changed
      shell: >
        systemctl status log4j-cve-2021-44228-hotpatch | grep -q 'log4j-cve-2021-44228-hotpatch.service - Run the CVE-2021-44228 hotfix script'  && echo 'Present' || echo 'Absent' 
      register: dd1_cli
      changed_when: dd1_cli.stdout == 'Present'

    - debug:
        msg: "{{dd1_cli.stdout}}"

    - name: log4j is running when result equals changed
      shell: >
        systemctl status log4j-cve-2021-44228-hotpatch  | grep -q '(running)'  && echo 'Running' || echo 'Stopped' 
      register: dd2_cli
      changed_when: dd2_cli.stdout == 'Running'

    - debug:
        msg: "{{dd2_cli.stdout}}"
#        msg: "{{dd2_cli | json_query(myquery) }}"
#      vars:
#        myquery: "[?stdout==`Running`]"


