### sudo ansible-playbook plays/stop-dd-srv.yml --private-key ~/.ssh/ssh-key.pem -i aws_ec2.yml

- name: Ensure the dd-agent service is disabled and stopped
  hosts: _Development

  tasks:
     - service:
         name: datadog-agent
         state: stopped
         enabled: no
