---
# tasks file for roles/aws-ami
###
###
- name: Create a temp ec2 instance
  ec2:
    region: "{{region}}"
    image: "{{base_ami}}"
    instance_type: "{{spot_instance_types}}"
    vpc_subnet_id: "{{subnet_id}}"
    group_id: "{{security_group_id}}"
    key_name: "{{provkey}}"
    instance_tags:
      Name: Adrian-test-1
    count: 1
    state: present
    tenancy: default
    termination_protection: no
    ebs_optimized: yes
    wait: yes
    spot_wait_timeout: 900
    instance_initiated_shutdown_behavior: stop
    assign_public_ip: no
    source_dest_check: true
  register: this_instance

- name: Store instance info
  set_fact:
    this_instance_info: "{{this_instance.instances.0}}"

- debug:
    msg: "{{this_instance_info.private_ip}} {{this_instance_info.id}}"
